### ISSUE TITLE
Colab: Prediction failed due to cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by Daryl149** [saic-mdal/lama#117]
When running the google colab on a self uploaded JPG file, the predict script fails. 
Checking the predict.log gives the following error:
`[2022-05-14 20:10:56,972][__main__][CRITICAL] - Prediction failed due to cuDNN error: CUDNN_STATUS_NOT_INITIALIZED`

**Update:**
Same error on uploaded PNG, and when predicting on the predefined photo
`fname = 'https://ic.pics.livejournal.com/mostovoy/28566193/1224276/1224276_original.jpg' # <-in the example`

**Update 2:**
There are a few possible causes for this error, most often it's an out of memory issue in disguise according to:
https://stackoverflow.com/questions/53698035/failed-to-get-convolution-algorithm-this-is-probably-because-cudnn-failed-to-in/56511889#56511889
However, it also fails on very small image size (JPG of 282x212), so I don't think it's a RAM/VRAM issue. 
Running `!nvidia-smi` reports that 0MB of VRAM is used.
Running `!top` reports that 10GB is in use, while 3GB is free.
So it could be a nvidia, cuda, cudnn driver version mismatch issue

**Comment by windj007** [comment]
It might be due to hardware or library settings changed by colab... I've just checked the colab and it worked. Are you still facing the problem?

**Comment by senya-ashukha** [comment]
Hi @Daryl149!

Huge thanks for reporting! Fixed it. Torch installation got broken somehow .. https://discuss.pytorch.org/t/runtimeerror-cudnn-error-cudnn-status-not-initialized/115286
